name: Deploy FullStackApp
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - run: docker build -t chickennight/react-test-app -f ./frontend/Dockerfile.dev ./frontend
      - run: docker run -e CI=true chickennight/react-test-app npm test

      - run: docker build -t chickennight/docker-frontend ./frontend
      - run: docker build -t chickennight/docker-nginx ./nginx
      - run: docker build -t chickennight/docker-backend ./backend

      - run: docker push chickennight/docker-frontend
      - run: docker push chickennight/docker-nginx
      - run: docker push chickennight/docker-backend

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: docker-fullstack-app
          environment_name: Docker-fullstack-app-env
          existing_bucket_name: elasticbeanstalk-ap-northeast-2-507006584994
          region: ap-northeast-2
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
